sonata_admin:
    title: 'Acueducto Quituro'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
            - { type: App\Block\MenuBlockService, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
