# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    monthly_invoice_value: 10000
    subscription_value: 700000

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Admin/'
            - '../src/EventListener'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.user:
        class: App\Admin\UserAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\User, controller: App\Controller\UserAdminController, manager_type: orm, group: Users, label: Admin User }
        calls:
            - [addChild, ['@admin.invoice', 'invoices']]

    admin.invoice:
        class: App\Admin\InvoiceAdmin
        arguments:
            - '@request_stack'
        tags:
            - { name: sonata.admin, model_class: App\Entity\Invoice, controller: App\Controller\InvoiceAdminController, manager_type: orm, group: Invoices, label: Admin Invoice }

    admin.payment:
        class: App\Admin\PaymentAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Payment, controller: App\Controller\PaymentAdminController, manager_type: orm, group: Payments, label: Admin Payment }

    App\EventListener\UserSaveListener:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.password_hasher'
            - '%monthly_invoice_value%'
        tags:
            - { name: doctrine.orm.entity_listener }

    App\EventListener\InvoiceListener:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'
        tags:
            - { name: doctrine.orm.entity_listener }